### PR TITLE
Use BasicObject instead of custom Blank class

### PR DESCRIPTION
**Pull request by timriley**
There was a bug reported to dry-data (dryrb/dry-data#12) about Kleisli's `Blank` class causing conflicts when used alongside Rails/ActiveSupport.

It looks like we can do without this custom `Blank` class now that Ruby has `BasicObject` built in – it does everything Jim Weirich’s original “BlankSlate” code offered (with no monkey-patching required, so hopefully this'll reduce any chance of conflicts with other code).

### CODE REVIEW

**Comment by kirs** [comment]
It works! @txus

**Comment by solnic** [comment]
@txus can we do something to help in merging this in and having it released? it seems like a reasonable change. Looks like CI is failing due to some bundler issues.

**Comment by txus** [comment]
Thank you @timriley! Sorry for the delay :)

**Comment by flash-gordon** [comment]
Hi @txus, what about new gem version?

**Comment by backus** [comment]
@txus any chance you could release a new version on rubygems soon? I'd love to benefit from the work in this PR

**Pull request merged**
