### PR TITLE
Add Try#to_either

### LINKED ISSUE #12: Kleisli::Try#to_either
I’d like to do this:

```ruby
xml_string = "…"
Try {
  Nokogiri::XML(xml_string)
}.to_either >-> doc {
  text = doc.xpath
  if text
    Right(text)
  else
    Left("no text found")
  end
}
```

Would this even be a good idea? If you agree that it would be useful, I’ll implement it and send you a PR.

### PR DESCRIPTION
**Pull request by maser**
Closes #12

### CODE REVIEW

**Comment by txus** [comment]
Thank you!

**Comment by waterlink** [comment]
:+1:

**Comment by waterlink** [comment]
BTW, this should have added an update to `Try` section of README.md too

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-05 15:16 GMT+02:00 Josep M. Bach <notifications@github.com>:

**Comment by maser** [comment]
@waterlink You're right, I'll create another PR.

**Comment by abevoelker** [comment]
Cool, would it be possible to get a new gem released?

**Pull request merged**
